/**
 * The now-sdk command catalogue.
 *
 * Generated by reading `now-sdk --help` and every subcommand's `--help` at
 * **4.9.2**, then hand-classifying two things a help string cannot tell you:
 *
 *  1. `risk` — you cannot derive "this writes to a production instance"
 *     from yargs output. `install` reaches the instance; `build` does not.
 *     Anything absent from this manifest defaults to always-ask.
 *  2. `picker` — WHICH picker resolves a flag's value. This is the whole
 *     point of the Project pane: nobody should have to go and find a sys_id.
 *
 * Regenerating: run `now-sdk --help` and `now-sdk <cmd> --help` for each
 * command and diff against this table.
 */

export const MANIFEST_SDK_VERSION = '4.9.2'

/** What resolves a flag's value in the UI. */
export type PickerKind =
  | 'app-scope' // sys_app records → sys_id
  | 'auth-alias' // now-sdk auth --list
  | 'directory' // local directory tree
  | 'enum' // fixed choices from --help
  | 'none' // free text
  | 'scope-name' // global | x_... (validated)
  | 'table' // sys_db_object
  | 'table-multi' // comma-separated table names

export type SdkRisk =
  /** Reaches the instance — always-ask, same tier as xml import. */
  | 'instance'
  /** Local only — no approval. */
  | 'local'
  /** Writes local files — confirm overwrites. */
  | 'local-write'

export interface SdkFlag {
  choices?: string[]
  /** Short description lifted from --help. */
  description: string
  name: string
  picker: PickerKind
  /** Positional argument rather than a --flag. */
  positional?: boolean
  required?: boolean
  type: 'boolean' | 'number' | 'string'
  /** Regex the value must satisfy, with a human explanation. */
  validate?: { message: string; pattern: RegExp }
}

export interface SdkCommand {
  flags: SdkFlag[]
  /** Prompts via @inquirer/prompts — must use the foreground handoff. */
  interactive?: boolean
  name: string
  /** npm script that wraps this command, when the project defines one. */
  npmScript?: 'build' | 'deploy'
  risk: SdkRisk
  summary: string
}

/** now.config.json's own schema for `scope`. Enforce before spawning. */
export const SCOPE_NAME_PATTERN = /^((sn|x)_[\da-z_]+|global)$/
export const SCOPE_NAME_MAX = 18

const AUTH_FLAG: SdkFlag = {
  description: 'Credential alias to use for authentication with instance',
  name: 'auth',
  picker: 'auth-alias',
  type: 'string',
}

export const SDK_COMMANDS: SdkCommand[] = [
  {
    flags: [
      { description: 'List all available authentication credentials', name: 'list', picker: 'none', type: 'boolean' },
      { description: 'Alias of credential to use by default (changes the SDK-wide default)', name: 'use', picker: 'auth-alias', type: 'string' },
    ],
    name: 'auth',
    risk: 'local-write',
    summary: 'List configured credentials, or change the default alias',
  },
  {
    flags: [
      {
        description: 'sys_id of a scoped app on the instance, or a path to a legacy app directory',
        name: 'from',
        picker: 'app-scope',
        type: 'string',
      },
      { description: 'Name of the ServiceNow app project', name: 'appName', picker: 'none', type: 'string' },
      { description: 'Package name (npm naming conventions)', name: 'packageName', picker: 'none', type: 'string' },
      {
        description: 'Scope name — vendor prefix required, max 18 chars',
        name: 'scopeName',
        picker: 'scope-name',
        type: 'string',
        validate: {
          message: `must match ${String(SCOPE_NAME_PATTERN)} and be ≤${SCOPE_NAME_MAX} characters`,
          pattern: SCOPE_NAME_PATTERN,
        },
      },
      {
        choices: ['base', 'javascript.aiux', 'javascript.basic', 'javascript.react', 'typescript.basic', 'typescript.react', 'typescript.vue'],
        description: 'Project template',
        name: 'template',
        picker: 'enum',
        type: 'string',
      },
      AUTH_FLAG,
    ],
    name: 'init',
    risk: 'local-write',
    summary: 'Scaffold a new app, or convert an existing scoped app into Fluent',
  },
  {
    flags: [
      { description: 'Validate that keys.ts is up to date (CI guard)', name: 'frozenKeys', picker: 'none', type: 'boolean' },
      { description: 'Treat sys_id conflicts as errors instead of warnings', name: 'errorOnConflict', picker: 'none', type: 'boolean' },
      { description: 'Skip cleaning build output first', name: 'skipClean', picker: 'none', type: 'boolean' },
      { description: 'Directory containing package.json', name: 'source', picker: 'directory', positional: true, type: 'string' },
    ],
    name: 'build',
    npmScript: 'build',
    risk: 'local',
    summary: 'Compile Fluent sources into an installable package',
  },
  {
    flags: [
      { description: 'Directory containing package.json', name: 'source', picker: 'directory', type: 'string' },
      { description: 'Uninstall and reinstall — metadata only on the instance WILL BE LOST', name: 'reinstall', picker: 'none', type: 'boolean' },
      { description: 'Install demo data', name: 'demoData', picker: 'none', type: 'boolean' },
      { description: 'Skip activating (publishing) flows after install', name: 'skip-flow-activation', picker: 'none', type: 'boolean' },
      { description: 'Report the most recent install of this app (read-only)', name: 'info', picker: 'none', type: 'boolean' },
      { description: 'Open the sys_app page in a browser on success', name: 'open-browser', picker: 'none', type: 'boolean' },
      AUTH_FLAG,
    ],
    name: 'install',
    npmScript: 'deploy',
    risk: 'instance',
    summary: 'Install or update the application on the instance',
  },
  {
    flags: [
      { description: 'Comma-separated tables to transform by hierarchy', name: 'table', picker: 'table-multi', type: 'string' },
      { description: 'Path to local XML file(s)/directory to transform', name: 'from', picker: 'directory', type: 'string' },
      { description: 'Directory containing package.json', name: 'directory', picker: 'directory', type: 'string' },
      { description: 'Allow descendant tables without their parent hierarchy', name: 'force', picker: 'none', type: 'boolean' },
      AUTH_FLAG,
    ],
    name: 'transform',
    risk: 'local-write',
    summary: 'Convert instance records or local XML into Fluent source',
  },
  {
    flags: [
      { description: 'Table to add as a dependency (e.g. actions, sys_security_acl)', name: 'add', picker: 'table', type: 'string' },
      { description: 'Scope for the dependency — required with --add', name: 'scope', picker: 'scope-name', type: 'string' },
      { description: 'Download only script type definitions (glide.*.d.ts)', name: 'type-defs-only', picker: 'none', type: 'boolean' },
      { description: 'Download only fluent types from now.config.json', name: 'fluent-only', picker: 'none', type: 'boolean' },
      { description: 'Directory containing package.json', name: 'directory', picker: 'directory', type: 'string' },
      AUTH_FLAG,
    ],
    name: 'dependencies',
    risk: 'local-write',
    summary: 'Download dependency metadata and TypeScript type definitions',
  },
  {
    flags: [
      { description: 'Directory to expand the application into', name: 'directory', picker: 'directory', positional: true, required: true, type: 'string' },
      { description: 'Download incrementally', name: 'incremental', picker: 'none', type: 'boolean' },
      { description: 'Directory containing package.json', name: 'source', picker: 'directory', type: 'string' },
    ],
    name: 'download',
    risk: 'local-write',
    summary: 'Download application metadata from the instance',
  },
  {
    flags: [{ description: 'Directory containing package.json', name: 'source', picker: 'directory', positional: true, type: 'string' }],
    name: 'pack',
    risk: 'local',
    summary: 'Zip the built app into an installable artifact',
  },
  {
    flags: [{ description: 'Directory containing package.json', name: 'source', picker: 'directory', positional: true, type: 'string' }],
    name: 'clean',
    risk: 'local',
    summary: 'Clean the output directory',
  },
  {
    flags: [
      { description: 'Topic name or keyword', name: 'topic', picker: 'none', positional: true, type: 'string' },
      { description: 'List topics', name: 'list', picker: 'none', type: 'boolean' },
      { choices: ['pretty', 'raw'], description: 'Output format', name: 'format', picker: 'enum', type: 'string' },
    ],
    name: 'explain',
    risk: 'local',
    summary: 'Fluent SDK documentation (offline — no instance needed)',
  },
]

/**
 * Commands that prompt and therefore need the foreground handoff. `auth
 * --add` asks for a password via @inquirer/prompts; the TUI deliberately
 * does not collect credentials itself, so it is not offered as a form —
 * it is handed the terminal. `init` prompts when required options are
 * missing, which the pane avoids by resolving them up front.
 */
export const INTERACTIVE_COMMANDS = new Set(['auth'])

export function findCommand(name: string): SdkCommand | undefined {
  return SDK_COMMANDS.find((c) => c.name === name)
}

/**
 * Risk for a command name. Unknown commands are treated as
 * instance-reaching: the safe default when the manifest is out of date
 * relative to the installed SDK.
 */
export function riskFor(name: string): SdkRisk {
  return findCommand(name)?.risk ?? 'instance'
}

export function validateFlagValue(flag: SdkFlag, value: string): string | undefined {
  if (flag.picker === 'scope-name' && value.length > SCOPE_NAME_MAX) {
    return `${value.length} characters — the maximum is ${SCOPE_NAME_MAX}`
  }

  if (flag.validate && value.length > 0 && !flag.validate.pattern.test(value)) {
    return flag.validate.message
  }

  if (flag.choices && value.length > 0 && !flag.choices.includes(value)) {
    return `must be one of: ${flag.choices.join(', ')}`
  }

  return undefined
}

/** Build the argv for a command from resolved flag values. */
export function buildArgv(command: SdkCommand, values: Record<string, string>): string[] {
  const argv: string[] = [command.name]
  for (const flag of command.flags) {
    const value = values[flag.name]
    if (value === undefined || value === '') continue
    if (flag.positional) {
      argv.push(value)
    } else if (flag.type === 'boolean') {
      if (value === 'true') argv.push(`--${flag.name}`)
    } else {
      argv.push(`--${flag.name}`, value)
    }
  }

  return argv
}
