var mess = new sn_ws.RESTMessageV2();
mess.setHttpMethod("GET");
mess.setEndpoint("https://ts1-44464216.onelearndns.com");
mess.setLogLevel("all");
var resp = mess.execute();
gs.info(resp.getStatusCode());
gs.debug("test debug");
gs.error("test error");
resp = mess.execute();
gs.info(resp.getStatusCode());
gs.debug("test debug");
gs.error("test error");
resp = mess.execute();
gs.info(resp.getStatusCode());
gs.debug("test debug");
gs.error("test error");